#%RAML 1.0
title: craft_project1

/notes:
  description: get submitted notes
  get:
    responses:
      200:
        body:
          application/json:
            example:
              [
                {
                  "id":1,
                  "title":"Morning routine",
                  "content":"This morning routine involved 2 hours of workout at the gym",
                  "createdAt":9-22-2021,
                  "updatedAt":9-22-2021
                },
                {
                  "id":2,
                  "title":"Afternoon routine",
                  "content":"This Afternoon routine involved 2 hours of workout at the gym",
                  "createdAt":9-22-2021,
                  "updatedAt":9-22-2021
                },
                {
                  "id":3,
                  "title":"Evening routine",
                  "content":"This Evening routine involved 2 hours of workout at the gym",
                  "createdAt":9-22-2021,
                  "updatedAt":9-22-2021
                }
              ]      
      404:
        body:
          application/json:
            example:
              {
                "msg": "Resource not Found"
              }
      500:
          body:
            application/json:
              example:
                {
                  "msg": "Internal Server Error"
                }
  post:
    body:
      application/json:
        example:
          [
             {
               "id":1,
               "title":"Morning routine",
               "content":"This morning routine involved 2 hours of workout at the gym",
               "createdAt":9-22-2021,
               "updatedAt":9-22-2021
             }
          ]       
        
  /{noteid}:
    description: get the note specified in the uri parameter "noteid" (shouldn't return null)
    get:
      description: basic http methods
      responses:
        200:
          body:
            application/json:
              example:
                {
                  "id":1,
                  "title":"Morning routine",
                  "content":"This morning routine involved 2 hours of workout at the gym",
                  "createdAt":9-22-2021,
                  "updatedAt":9-22-2021
                }
        404:
          body:
            application/json:
              example:
                {
                  "msg":"Resource Not Found"
                }
        500:
          body:
            application/json:
              example:
                {
                  "msg": "Internal Server Error"
                }

    put:

    delete:
    
  
  

