#%RAML 1.0 Library
types:
  datatype:  !include Datatypes/datatypenote.raml
traits:
  collections: !include trait.raml
resourceTypes:
  myresource: !include resourceType.raml
  myresource2: !include resourceType2.raml