#%RAML 1.0 Overlay
extends: craft-b21-final-project.raml

usage: spanish users
documentation:
  - title: introduction
    content: this doc is for spanish users only
/notes:
  description: note response have get http method
