#%RAML 1.0 NamedExample
 {
                   "noteid":1,
                  "title":"Morning routine",
                  "content":"This morning routine involved 2 hours of workout at the gym",
                  "createdAt": 2021-07-03T21:00:00,
                   "updatedAt": 2021-07-04T21:00:00,          
      }