#%RAML 1.0 SecurityScheme
type: Basic Authentication
describedBy:
  headers:
    noteid:
      description: send noteid
      type: integer
  responses:
    403:
      description: credentional is required
    
    
  
    